CREATE TABLE IF NOT EXISTS projects(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  priority integer NOT NULL,
  description text,
  deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  done boolean,
  project_id integer REFERENCES projects(id)
);

insert into projects (name, priority, description, deliverydate) values
('Make a Web App', 1, 'Using EXPRESS y POSTGRES', '2021-02-12'),
('Make a Mobile App', 1, 'Using Flutter', '2021-02-16'),
('Make a Desktop App', 2, 'Using Electron', '2021-03-20');

select * from projects p ;

insert into tasks (name, done, project_id) values
('Learn EXPRESS JS', false, 1),
('Create Mockup', false, 1),
('Download FLUTTER', true, 2);

select * from tasks t ;